---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    name: PR labels
    uses: ./.github/workflows/pr-labels.yaml
