---
name: Validate Renovate preset

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    name: Renovate preset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "24"
      - name: Validate Renovate preset
        run: >-
          npx --yes --package=renovate@44.65.0 renovate-config-validator
          --strict renovate-base.json renovate-python.json .github/renovate.json
